# Generated by Django 5.0.7 on 2024-07-26 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="statuse",
            new_name="status",
        ),
    ]
